# (PART) Interactive Exercises {-}

# Asking and Answering Research Questions {#chapter-01}

If you prefer to use for the exercises your phone or tablet, [scan the associated QR code](qr-codes.html#chapter-1).

## Interactive Video {#chap01-video}


```{block2, help-video1, type='rmdinfo'}
If you dont know how to use the video exercise go to the [help picture in the appendix](#help-interactive-video). 
```

### Research questions {#chap01-video-research-questions}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=49" width="958" height="665" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

### Meta-analysis {#chap01-video-meta-analysis}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=47" width="958" height="665" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

### Open Science {#chap01-video-open-science}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=51" width="958" height="665" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

## Glossary {#chap01-glossary}

### Accordion {#chap01-glossary-accordion}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=20" width="958" height="879" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

### Dialog Cards {#chap01-glossary-dialog-cards}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=56" width="960" height="621" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

### Drag words {#chap01-glossary-drag-words}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=55" width="958" height="864" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

### Memory Game {#chap01-glossary-memory-game}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=14" width="958" height="1083" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

### Fill in the Blanks {#chap01-glossary-fill-in-the-blanks}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=24" width="958" height="1372" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

### Flash Cards {#chap01-glossary-flash-cards}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=57" width="960" height="927" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

## Poll Intuitions {#chap01-poll-intuitions-true-false}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=30" width="958" height="246" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

## Research Process

### Drag & Drop {#chap01-research-process-drag-n-drop}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=16" width="958" height="1073" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>


### Form Wizard {#chap01-sketch-research-form-wizard}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=19" width="958" height="740" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

### Interactive Video {#chap01-video-header-not-in-use}


```{block2, chap01-go-to-video, type='rmdinquiry'}

See the [Video under heading of 'Interactive Video'](#chap01-video-research-questions).
```




### Order of Steps {#chap01-order-of-steps}

#### Research Process (Summary) {#chap01-research-process-phases-summary}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=36" width="958" height="454" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

#### Estimation Plan (Image Sequencing) {#chap01-estimation-plan-image-sequencing}

<!--
<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=37" width="960" height="760" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>
-->


```{block2, chap01-image-sequencing, type='rmdinquiry'}
Integrating this exercise into this books destroys the internal linking. It seems to me a bug of the H5P image sequenceing content type. 

Therefore I have provided a <a href="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=37" target="_blank">link to my WordPress Blog</a>.
```




#### Estimation Plan (Summary) {#chap01-estimation-plan-summary}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=53" width="958" height="461" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>


#### Research & Estimation (LearnR) {#chap01-steps-learnr}


```{block2, 03-shiny-order-steps, type='rmdinquiry'}
Go to Shiny app: [Order Steps of the Research Process](https://pbaumgartner.shinyapps.io/itns-research-steps/#section-research-process).
```




## Meta-Analysis {#chap01-meta-analysis}

### Explore Forest Plot (Image Hotspots) {#chap01-forest-plot-info-hotspots}

<center>**Click at the points with the question mark to learn what they signify**</center>
<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=26" width="960" height="434" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>


### Point Estimates in Forest Plot (Find Multiple Hotspots) {#chap01-find-point-estimates-find-hotspots}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=27" width="958" height="455" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

## Reporting (Accordion) {#chap01-reporting-accordion}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=46" width="958" height="252" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

## Quizzes and Assessment {#chap01-quizzes}

### Quiz 1 (Question Set) {#chap01-quiz-1}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=12" width="958" height="393" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

### Quiz 2 (Question Set) {#chap01-quiz-2}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=25" width="958" height="362" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

### Take-Home Messages (Summary) {#chap01-take-home}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=79" width="960" height="301" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>


### Assessment (Question Set) {#chap01-assessment}

<iframe src="https://peter.baumgartner.name/wp-admin/admin-ajax.php?action=h5p_embed&id=81" width="960" height="319" frameborder="0" allowfullscreen="allowfullscreen"></iframe><script src="https://peter.baumgartner.name/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>


